{
  "enabled_plugins":
    [
      "Basic Calculator",
      "Hash plugin",
      "Tor check plugin",
      "Open Access DOI rewrite",
      "Hostnames plugin",
      "Unit converter plugin",
      "Tracker URL remover",
    ],
  "engines":
    [
      { "disabled": true, "name": "1x" },
      { "disabled": false, "name": "artic" },
      { "disabled": true, "name": "bing" },
      { "disabled": false, "name": "bing images" },
      { "disabled": false, "name": "bing videos" },
      { "disabled": true, "name": "brave" },
      { "disabled": true, "name": "brave.images" },
      { "disabled": true, "name": "brave.news" },
      { "disabled": true, "name": "brave.videos" },
      { "disabled": false, "name": "crowdview", "weight": 0.5 },
      { "disabled": true, "name": "curlie" },
      { "disabled": false, "name": "currency" },
      { "disabled": true, "name": "dailymotion" },
      { "disabled": false, "name": "ddg definitions", "weight": 2 },
      { "disabled": false, "name": "deviantart" },
      { "disabled": true, "name": "dictzone" },
      { "disabled": false, "name": "duckduckgo" },
      { "disabled": false, "name": "duckduckgo images" },
      { "disabled": false, "name": "duckduckgo videos" },
      { "disabled": false, "name": "flickr" },
      { "disabled": false, "name": "google images" },
      { "disabled": false, "name": "google news" },
      { "disabled": true, "name": "google play movies" },
      { "disabled": false, "name": "google videos" },
      { "disabled": false, "name": "imgur" },
      { "disabled": false, "name": "invidious" },
      { "disabled": false, "name": "library of congress" },
      { "disabled": true, "name": "lingva" },
      { "disabled": true, "name": "material icons", "weight": 0.2 },
      { "disabled": false, "name": "mojeek" },
      { "disabled": false, "name": "mwmbl", "weight": 0.4 },
      { "disabled": true, "name": "odysee" },
      { "disabled": false, "name": "openverse" },
      { "disabled": false, "name": "peertube" },
      { "disabled": true, "name": "pinterest" },
      { "disabled": true, "name": "piped" },
      { "disabled": true, "name": "qwant" },
      { "disabled": true, "name": "qwant images" },
      { "disabled": false, "name": "qwant videos" },
      { "disabled": false, "name": "rumble" },
      { "disabled": false, "name": "sepiasearch" },
      { "disabled": false, "name": "svgrepo" },
      { "disabled": false, "name": "unsplash" },
      { "disabled": false, "name": "vimeo" },
      { "disabled": false, "name": "wallhaven" },
      { "disabled": false, "name": "wikibooks" },
      { "disabled": false, "name": "wikicommons.images" },
      { "disabled": false, "name": "wikidata" },
      { "disabled": false, "name": "wikiquote" },
      { "disabled": false, "name": "wikisource" },
      { "disabled": false, "name": "wikispecies", "weight": 0.5 },
      { "disabled": false, "name": "wikiversity", "weight": 0.5 },
      { "disabled": false, "name": "wikivoyage", "weight": 0.5 },
      { "disabled": true, "name": "yacy images" },
      { "disabled": false, "name": "youtube" },
    ],
  "general":
    {
      "contact_url": false,
      "debug": false,
      "donation_url": false,
      "enable_metrics": false,
      "instance_name": "xvrqt search",
      "privacypolicy_url": false,
    },
  "outgoing":
    {
      "enable_http2": true,
      "max_request_timeout": 15.0,
      "pool_connections": 100,
      "pool_maxsize": 15,
      "request_timeout": 5.0,
    },
  "redis": { "url": "unix:///run/redis-searx/redis.sock" },
  "search":
    {
      "autocomplete": "duckduckgo",
      "autocomplete_min": 2,
      "ban_time_on_fail": 5,
      "formats": ["html", "json"],
      "max_ban_time_on_fail": 120,
      "safe_search": 1,
    },
  "server":
    {
      "base_url": "https://search.irlqt.net",
      "bind_address": "127.0.0.1",
      "image_proxy": true,
      "limiter": false,
      "method": "GET",
      "port": 3452,
      "public_instance": false,
      "secret_key": "gaygirls",
    },
  "ui":
    {
      "center_alignment": true,
      "default_locale": "en",
      "default_theme": "simple",
      "hotkeys": "vim",
      "infinite_scroll": true,
      "query_in_title": true,
      "search_on_category_select": true,
      "static_use_hash": true,
      "theme_args": { "simple_style": "auto" },
    },
  "use_default_settings": true,
  "valkey": { "url": "unix:///run/redis-searx/redis.sock" },
}
